services:
  # Service Backend Fastify
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: transcendance-backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development
      - DATABASE_PATH=/app/data/database.sqlite
    volumes:
      - backend_data:/app/data
      - backend_uploads:/app/uploads
      - backend_node_modules:/app/node_modules
    networks:
      - transcendance-network
    restart: unless-stopped
    
  # Service Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: transcendance-frontend
    ports:
      - "8080:443"
    depends_on:
      - backend
    networks:
      - transcendance-network
    restart: unless-stopped

volumes:
  backend_data:
    driver: local
  backend_uploads:
    driver: local
  backend_node_modules:
    driver: local

networks:
  transcendance-network:
    driver: bridge